"""
Rule engine for detecting suspicious cross-zone movement patterns.

The core logic: detect when someone who paid for one service is using another.
Primary pattern: Range → Short Game (collect balls) → Range = theft.
"""

import time
from dataclasses import dataclass, field
from enum import Enum

from loguru import logger

from src.zones.zone_engine import ZoneEvent


class AlertSeverity(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class AlertType(str, Enum):
    CROSS_ZONE_THEFT = "cross_zone_theft"
    UNPAID_RANGE_USE = "unpaid_range_use"
    BALL_COLLECTION = "ball_collection"
    SUSPICIOUS_PATTERN = "suspicious_pattern"


@dataclass
class Alert:
    """An alert generated by the rule engine."""
    id: str
    alert_type: AlertType
    severity: AlertSeverity
    person_id: int
    message: str
    timestamp: float = field(default_factory=time.time)
    camera_id: str | None = None
    zone_path: list[str] = field(default_factory=list)
    snapshot: bytes | None = None  # JPEG-encoded person snapshot
    acknowledged: bool = False

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "alert_type": self.alert_type.value,
            "severity": self.severity.value,
            "person_id": self.person_id,
            "message": self.message,
            "timestamp": self.timestamp,
            "camera_id": self.camera_id,
            "zone_path": self.zone_path,
            "acknowledged": self.acknowledged,
        }


@dataclass
class PersonMovementHistory:
    """Tracks a person's zone movement for pattern analysis."""
    global_id: int
    zone_sequence: list[tuple[str, float]] = field(default_factory=list)  # (zone, timestamp)
    current_zone: str | None = None
    last_alert_time: float = 0.0

    def add_zone_visit(self, zone: str, timestamp: float):
        """Record entering a new zone."""
        if not self.zone_sequence or self.zone_sequence[-1][0] != zone:
            self.zone_sequence.append((zone, timestamp))
        self.current_zone = zone

    def get_recent_zones(self, window: float) -> list[tuple[str, float]]:
        """Get zone visits within the last N seconds."""
        cutoff = time.time() - window
        return [(z, t) for z, t in self.zone_sequence if t >= cutoff]


class RuleEngine:
    """
    Evaluates movement patterns against rules to detect revenue leakage.

    Rules:
    1. Cross-zone theft: Person at range → enters short game → returns to range
    2. Unpaid usage: Person detected at range with no payment record
    3. Ball collection: Person spending time in short game area picking up balls
       then moving to range
    """

    def __init__(self, time_window: int = 1800, min_dwell_time: int = 120,
                 cooldown: int = 300):
        self.time_window = time_window      # 30 min window for pattern detection
        self.min_dwell_time = min_dwell_time  # 2 min min stay in a zone
        self.cooldown = cooldown            # 5 min between re-alerting same person

        self._histories: dict[int, PersonMovementHistory] = {}
        self._alerts: list[Alert] = []
        self._alert_counter = 0
        self._alert_callbacks: list[callable] = []

    def on_alert(self, callback: callable):
        """Register a callback for when alerts are generated."""
        self._alert_callbacks.append(callback)

    def process_zone_events(self, events: list[ZoneEvent]) -> list[Alert]:
        """
        Process zone events and check for suspicious patterns.

        Args:
            events: New zone entry/exit events

        Returns:
            List of new alerts generated
        """
        new_alerts = []

        for event in events:
            if event.event_type != "enter":
                continue  # We only care about zone entries

            # Get or create movement history
            history = self._histories.get(event.person_id)
            if history is None:
                history = PersonMovementHistory(global_id=event.person_id)
                self._histories[event.person_id] = history

            history.add_zone_visit(event.zone, event.timestamp)

            # Check all rules
            alerts = self._check_rules(history, event)
            new_alerts.extend(alerts)

        return new_alerts

    def _check_rules(self, history: PersonMovementHistory,
                     event: ZoneEvent) -> list[Alert]:
        """Run all rules against a person's movement history."""
        alerts = []

        # Rule 1: Cross-zone theft (Range → Short Game → Range)
        alert = self._check_cross_zone_theft(history, event)
        if alert:
            alerts.append(alert)

        # Rule 2: Reverse cross-zone (Short Game → Range without payment)
        alert = self._check_reverse_cross_zone(history, event)
        if alert:
            alerts.append(alert)

        return alerts

    def _check_cross_zone_theft(self, history: PersonMovementHistory,
                                event: ZoneEvent) -> Alert | None:
        """
        Detect: Person was at range → went to short game → returned to range.
        This is the primary theft pattern — collecting free balls.
        """
        now = time.time()

        # Cooldown check
        if now - history.last_alert_time < self.cooldown:
            return None

        recent = history.get_recent_zones(self.time_window)
        if len(recent) < 3:
            return None

        # Look for the pattern: range → short_game → range
        zones_only = [z for z, _ in recent]

        for i in range(len(zones_only) - 2):
            if (zones_only[i] == "Driving Range"
                    and zones_only[i + 1] == "Short Game Area"
                    and zones_only[i + 2] == "Driving Range"):

                # Check dwell time in short game area
                sg_enter = recent[i + 1][1]
                sg_exit = recent[i + 2][1]
                dwell = sg_exit - sg_enter

                if dwell >= self.min_dwell_time:
                    self._alert_counter += 1
                    alert = Alert(
                        id=f"ALT-{self._alert_counter:06d}",
                        alert_type=AlertType.CROSS_ZONE_THEFT,
                        severity=AlertSeverity.HIGH,
                        person_id=history.global_id,
                        message=(
                            f"Suspected ball theft: Person #{history.global_id} "
                            f"was at the range, spent {int(dwell)}s in the short game "
                            f"area, then returned to the range. Likely collected "
                            f"free balls."
                        ),
                        camera_id=event.camera_id,
                        zone_path=zones_only[i:i + 3],
                    )
                    self._alerts.append(alert)
                    history.last_alert_time = now

                    logger.warning(f"🚨 {alert.message}")
                    for cb in self._alert_callbacks:
                        cb(alert)

                    return alert

        return None

    def _check_reverse_cross_zone(self, history: PersonMovementHistory,
                                  event: ZoneEvent) -> Alert | None:
        """
        Detect: Person was at short game → went to range (using range without paying).
        """
        now = time.time()

        if now - history.last_alert_time < self.cooldown:
            return None

        recent = history.get_recent_zones(self.time_window)
        if len(recent) < 2:
            return None

        zones_only = [z for z, _ in recent]

        for i in range(len(zones_only) - 1):
            if (zones_only[i] == "Short Game Area"
                    and zones_only[i + 1] == "Driving Range"):

                dwell_at_sg = recent[i + 1][1] - recent[i][1]

                if dwell_at_sg >= self.min_dwell_time:
                    self._alert_counter += 1
                    alert = Alert(
                        id=f"ALT-{self._alert_counter:06d}",
                        alert_type=AlertType.UNPAID_RANGE_USE,
                        severity=AlertSeverity.MEDIUM,
                        person_id=history.global_id,
                        message=(
                            f"Possible unpaid range use: Person #{history.global_id} "
                            f"was in the short game area for {int(dwell_at_sg)}s, "
                            f"then moved to the driving range."
                        ),
                        camera_id=event.camera_id,
                        zone_path=zones_only[i:i + 2],
                    )
                    self._alerts.append(alert)
                    history.last_alert_time = now

                    logger.warning(f"⚠️ {alert.message}")
                    for cb in self._alert_callbacks:
                        cb(alert)

                    return alert

        return None

    def get_alerts(self, since: float | None = None, person_id: int | None = None,
                   alert_type: AlertType | None = None,
                   unacknowledged_only: bool = False) -> list[Alert]:
        """Query alerts with optional filters."""
        alerts = self._alerts
        if since is not None:
            alerts = [a for a in alerts if a.timestamp >= since]
        if person_id is not None:
            alerts = [a for a in alerts if a.person_id == person_id]
        if alert_type is not None:
            alerts = [a for a in alerts if a.alert_type == alert_type]
        if unacknowledged_only:
            alerts = [a for a in alerts if not a.acknowledged]
        return alerts

    def acknowledge_alert(self, alert_id: str) -> bool:
        """Mark an alert as acknowledged."""
        for alert in self._alerts:
            if alert.id == alert_id:
                alert.acknowledged = True
                return True
        return False

    def get_person_history(self, person_id: int) -> PersonMovementHistory | None:
        return self._histories.get(person_id)

    @property
    def total_alerts(self) -> int:
        return len(self._alerts)

    @property
    def active_alerts(self) -> int:
        return sum(1 for a in self._alerts if not a.acknowledged)
